// Code generated by ogen, DO NOT EDIT.

package hakoniwa

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetAuthMe implements getAuthMe operation.
//
// Get current user and instance status.
//
// GET /auth/me
func (UnimplementedHandler) GetAuthMe(ctx context.Context) (r GetAuthMeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetConfiguration implements getConfiguration operation.
//
// Get application configuration.
//
// GET /configuration
func (UnimplementedHandler) GetConfiguration(ctx context.Context) (r *Configuration, _ error) {
	return r, ht.ErrNotImplemented
}

// LoginAnonymous implements loginAnonymous operation.
//
// Login anonymously (creates session and instance).
//
// POST /auth/anonymous
func (UnimplementedHandler) LoginAnonymous(ctx context.Context) (r *AuthStatus, _ error) {
	return r, ht.ErrNotImplemented
}

// OidcAuthorize implements oidcAuthorize operation.
//
// Redirect to OIDC provider.
//
// GET /auth/oidc/authorize
func (UnimplementedHandler) OidcAuthorize(ctx context.Context) (r *OidcAuthorizeFound, _ error) {
	return r, ht.ErrNotImplemented
}

// OidcCallback implements oidcCallback operation.
//
// Process OIDC callback from IdP.
//
// GET /auth/oidc/callback
func (UnimplementedHandler) OidcCallback(ctx context.Context, params OidcCallbackParams) (r *OidcCallbackFound, _ error) {
	return r, ht.ErrNotImplemented
}
