// Code generated by ogen, DO NOT EDIT.

package hakoniwa

// setDefaults set default value of fields.
func (s *Configuration) setDefaults() {
	{
		val := string("OpenID Connect")
		s.OidcName.SetTo(val)
	}
	{
		val := bool(false)
		s.AuthAutoLogin = val
	}
}
