// Code generated by ogen, DO NOT EDIT.

package hakoniwa

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateInstance implements createInstance operation.
	//
	// Create a new instance.
	//
	// POST /instances
	CreateInstance(ctx context.Context, req *CreateInstanceRequest) (CreateInstanceRes, error)
	// DeleteInstance implements deleteInstance operation.
	//
	// Delete an instance.
	//
	// DELETE /instances/{instanceId}
	DeleteInstance(ctx context.Context, params DeleteInstanceParams) (DeleteInstanceRes, error)
	// GetAuthMe implements getAuthMe operation.
	//
	// Get current user status.
	//
	// GET /auth/me
	GetAuthMe(ctx context.Context) (GetAuthMeRes, error)
	// GetConfiguration implements getConfiguration operation.
	//
	// Get application configuration.
	//
	// GET /configuration
	GetConfiguration(ctx context.Context) (*Configuration, error)
	// ListInstanceTypes implements listInstanceTypes operation.
	//
	// List available instance types.
	//
	// GET /instance-types
	ListInstanceTypes(ctx context.Context) ([]InstanceType, error)
	// ListInstances implements listInstances operation.
	//
	// List user instances.
	//
	// GET /instances
	ListInstances(ctx context.Context) ([]Instance, error)
	// LoginAnonymous implements loginAnonymous operation.
	//
	// Login anonymously (creates session only).
	//
	// POST /auth/anonymous
	LoginAnonymous(ctx context.Context) (*AuthStatus, error)
	// Logout implements logout operation.
	//
	// Logout.
	//
	// POST /auth/logout
	Logout(ctx context.Context) error
	// OidcAuthorize implements oidcAuthorize operation.
	//
	// Redirect to OIDC provider.
	//
	// GET /auth/oidc/authorize
	OidcAuthorize(ctx context.Context) (*OidcAuthorizeFound, error)
	// OidcCallback implements oidcCallback operation.
	//
	// Process OIDC callback from IdP.
	//
	// GET /auth/oidc/callback
	OidcCallback(ctx context.Context, params OidcCallbackParams) (*OidcCallbackFound, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
