// Code generated by ogen, DO NOT EDIT.

package hakoniwa

import (
	"net/http"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
)

// OidcCallbackParams is parameters of oidcCallback operation.
type OidcCallbackParams struct {
	Code  string
	State string
	// Error code from IdP.
	Error OptString `json:",omitempty,omitzero"`
	// Error description from IdP.
	ErrorDescription OptString `json:",omitempty,omitzero"`
}

func unpackOidcCallbackParams(packed middleware.Parameters) (params OidcCallbackParams) {
	{
		key := middleware.ParameterKey{
			Name: "code",
			In:   "query",
		}
		params.Code = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "state",
			In:   "query",
		}
		params.State = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "error",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Error = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "error_description",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.ErrorDescription = v.(OptString)
		}
	}
	return params
}

func decodeOidcCallbackParams(args [0]string, argsEscaped bool, r *http.Request) (params OidcCallbackParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: code.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "code",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Code = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "code",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: state.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "state",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.State = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "state",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: error.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "error",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotErrorVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotErrorVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Error.SetTo(paramsDotErrorVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "error",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: error_description.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "error_description",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotErrorDescriptionVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotErrorDescriptionVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ErrorDescription.SetTo(paramsDotErrorDescriptionVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "error_description",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
