// Code generated by ogen, DO NOT EDIT.

package hakoniwa

import (
	"github.com/go-faster/errors"
)

// Ref: #/components/schemas/AuthStatus
type AuthStatus struct {
	User     User        `json:"user"`
	Instance OptInstance `json:"instance"`
}

// GetUser returns the value of User.
func (s *AuthStatus) GetUser() User {
	return s.User
}

// GetInstance returns the value of Instance.
func (s *AuthStatus) GetInstance() OptInstance {
	return s.Instance
}

// SetUser sets the value of User.
func (s *AuthStatus) SetUser(val User) {
	s.User = val
}

// SetInstance sets the value of Instance.
func (s *AuthStatus) SetInstance(val OptInstance) {
	s.Instance = val
}

func (*AuthStatus) getAuthMeRes() {}

// GetAuthMeUnauthorized is response for GetAuthMe operation.
type GetAuthMeUnauthorized struct{}

func (*GetAuthMeUnauthorized) getAuthMeRes() {}

// Ref: #/components/schemas/Instance
type Instance struct {
	Status InstanceStatus `json:"status"`
	PodIP  OptString      `json:"pod_ip"`
}

// GetStatus returns the value of Status.
func (s *Instance) GetStatus() InstanceStatus {
	return s.Status
}

// GetPodIP returns the value of PodIP.
func (s *Instance) GetPodIP() OptString {
	return s.PodIP
}

// SetStatus sets the value of Status.
func (s *Instance) SetStatus(val InstanceStatus) {
	s.Status = val
}

// SetPodIP sets the value of PodIP.
func (s *Instance) SetPodIP(val OptString) {
	s.PodIP = val
}

type InstanceStatus string

const (
	InstanceStatusPending     InstanceStatus = "pending"
	InstanceStatusRunning     InstanceStatus = "running"
	InstanceStatusTerminating InstanceStatus = "terminating"
)

// AllValues returns all InstanceStatus values.
func (InstanceStatus) AllValues() []InstanceStatus {
	return []InstanceStatus{
		InstanceStatusPending,
		InstanceStatusRunning,
		InstanceStatusTerminating,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s InstanceStatus) MarshalText() ([]byte, error) {
	switch s {
	case InstanceStatusPending:
		return []byte(s), nil
	case InstanceStatusRunning:
		return []byte(s), nil
	case InstanceStatusTerminating:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *InstanceStatus) UnmarshalText(data []byte) error {
	switch InstanceStatus(data) {
	case InstanceStatusPending:
		*s = InstanceStatusPending
		return nil
	case InstanceStatusRunning:
		*s = InstanceStatusRunning
		return nil
	case InstanceStatusTerminating:
		*s = InstanceStatusTerminating
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewOptInstance returns new OptInstance with value set to v.
func NewOptInstance(v Instance) OptInstance {
	return OptInstance{
		Value: v,
		Set:   true,
	}
}

// OptInstance is optional Instance.
type OptInstance struct {
	Value Instance
	Set   bool
}

// IsSet returns true if OptInstance was set.
func (o OptInstance) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInstance) Reset() {
	var v Instance
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInstance) SetTo(v Instance) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInstance) Get() (v Instance, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInstance) Or(d Instance) Instance {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/User
type User struct {
	// User ID (OpenID Connect sub or UUID).
	ID   string   `json:"id"`
	Type UserType `json:"type"`
}

// GetID returns the value of ID.
func (s *User) GetID() string {
	return s.ID
}

// GetType returns the value of Type.
func (s *User) GetType() UserType {
	return s.Type
}

// SetID sets the value of ID.
func (s *User) SetID(val string) {
	s.ID = val
}

// SetType sets the value of Type.
func (s *User) SetType(val UserType) {
	s.Type = val
}

type UserType string

const (
	UserTypeOpenidConnect UserType = "openid_connect"
	UserTypeAnonymous     UserType = "anonymous"
)

// AllValues returns all UserType values.
func (UserType) AllValues() []UserType {
	return []UserType{
		UserTypeOpenidConnect,
		UserTypeAnonymous,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s UserType) MarshalText() ([]byte, error) {
	switch s {
	case UserTypeOpenidConnect:
		return []byte(s), nil
	case UserTypeAnonymous:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *UserType) UnmarshalText(data []byte) error {
	switch UserType(data) {
	case UserTypeOpenidConnect:
		*s = UserTypeOpenidConnect
		return nil
	case UserTypeAnonymous:
		*s = UserTypeAnonymous
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
