// Code generated by ogen, DO NOT EDIT.

package hakoniwa

// OperationName is the ogen operation name
type OperationName = string

const (
	GetAuthMeOperation      OperationName = "GetAuthMe"
	LoginAnonymousOperation OperationName = "LoginAnonymous"
)
