// Code generated by ogen, DO NOT EDIT.
package hakoniwa

type CreateInstanceRes interface {
	createInstanceRes()
}

type DeleteInstanceRes interface {
	deleteInstanceRes()
}

type GetAuthMeRes interface {
	getAuthMeRes()
}
