// Code generated by ogen, DO NOT EDIT.

package hakoniwa

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateInstanceOperation    OperationName = "CreateInstance"
	DeleteInstanceOperation    OperationName = "DeleteInstance"
	GetAuthMeOperation         OperationName = "GetAuthMe"
	GetConfigurationOperation  OperationName = "GetConfiguration"
	ListInstanceTypesOperation OperationName = "ListInstanceTypes"
	ListInstancesOperation     OperationName = "ListInstances"
	LoginAnonymousOperation    OperationName = "LoginAnonymous"
	LogoutOperation            OperationName = "Logout"
	OidcAuthorizeOperation     OperationName = "OidcAuthorize"
	OidcCallbackOperation      OperationName = "OidcCallback"
)
