// Code generated by ogen, DO NOT EDIT.

package hakoniwa

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetAuthMe implements getAuthMe operation.
	//
	// Get current user and instance status.
	//
	// GET /auth/me
	GetAuthMe(ctx context.Context) (GetAuthMeRes, error)
	// GetConfiguration implements getConfiguration operation.
	//
	// Get application configuration.
	//
	// GET /configuration
	GetConfiguration(ctx context.Context) (*Configuration, error)
	// LoginAnonymous implements loginAnonymous operation.
	//
	// Login anonymously (creates session and instance).
	//
	// POST /auth/anonymous
	LoginAnonymous(ctx context.Context) (*AuthStatus, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
