apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hakoniwa-pod-manager
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete"]
