openapi: 3.0.3
info:
  title: Hakoniwa API
  version: 0.1.0
  description: API for Hakoniwa On-Demand Desktop Service
servers:
  - url: /_hakoniwa/api
paths:
  /auth/me:
    get:
      summary: Get current user status
      operationId: getAuthMe
      responses:
        '200':
          description: Authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthStatus'
        '401':
          description: Unauthorized (Not logged in)
  /auth/anonymous:
    post:
      summary: Login anonymously (creates session only)
      operationId: loginAnonymous
      responses:
        '200':
          description: Logged in successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthStatus'
  /auth/logout:
    post:
      summary: Logout
      operationId: logout
      responses:
        '200':
          description: Logged out successfully
  /auth/oidc/authorize:
    get:
      summary: Redirect to OIDC provider
      operationId: oidcAuthorize
      responses:
        '302':
          description: Redirect to OIDC provider
          headers:
            Location:
              schema:
                type: string
              description: URL to redirect to
              required: true
  /auth/oidc/callback:
    get:
      summary: Process OIDC callback from IdP
      operationId: oidcCallback
      parameters:
        - name: code
          in: query
          schema:
            type: string
          required: true
        - name: state
          in: query
          schema:
            type: string
          required: true
        - name: error
          in: query
          schema:
            type: string
          required: false
          description: Error code from IdP
        - name: error_description
          in: query
          schema:
            type: string
          required: false
          description: Error description from IdP
      responses:
        '302':
          description: Redirect to frontend
          headers:
            Location:
              schema:
                type: string
              description: URL to redirect to
              required: true
  /instances/{instanceId}:
    delete:
      summary: Delete an instance
      operationId: deleteInstance
      parameters:
        - name: instanceId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Instance deleted
        '404':
          description: Instance not found
  /instances:
    get:
      summary: List user instances
      operationId: listInstances
      responses:
        '200':
          description: List of instances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Instance'
    post:
      summary: Create a new instance
      operationId: createInstance
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateInstanceRequest'
      responses:
        '200':
          description: Instance created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Instance'
        '400':
          description: Bad Request (e.g., invalid instance type)
        '503':
          description: Max instances reached
  /instance-types:
    get:
      summary: List available instance types
      operationId: listInstanceTypes
      responses:
        '200':
          description: List of available instance types
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InstanceType'
  /configuration:
    get:
      summary: Get application configuration
      operationId: getConfiguration
      responses:
        '200':
          description: Application configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Configuration'

components:
  schemas:
    Configuration:
      type: object
      properties:
        title:
          type: string
          description: Application title
        message:
          type: string
          description: Welcome message
        logo_url:
          type: string
          description: URL to the application logo
        terms_of_service_url:
          type: string
          description: URL to the terms of service
        privacy_policy_url:
          type: string
          description: URL to the privacy policy
        auth_methods:
          type: array
          items:
            type: string
          description: List of enabled authentication methods (e.g. 'anonymous', 'oidc')
        oidc_name:
          type: string
          description: Display name for the OIDC login button
          default: OpenID Connect
        auth_auto_login:
          type: boolean
          description: Whether to automatically log in if only one auth method is available
          default: false
      required:
        - title
        - message
        - logo_url
        - auth_methods
        - auth_auto_login
    AuthStatus:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
      required:
        - user
    User:
      type: object
      properties:
        id:
          type: string
          description: User ID (OpenID Connect sub or UUID)
        type:
          type: string
          enum: [openid_connect, anonymous]
      required:
        - id
        - type
    Instance:
      type: object
      properties:
        id:
          type: string
          description: Unique instance ID
        name:
          type: string
          description: Display name of the instance
        type:
          type: string
          description: Type of the instance
        status:
          type: string
          enum: [pending, running, terminating]
        pod_ip:
          type: string
      required:
        - id
        - name
        - type
        - status
    CreateInstanceRequest:
      type: object
      properties:
        type:
          type: string
          description: Type of the instance to create
      required:
        - type
    InstanceType:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the instance type
        name:
          type: string
          description: Display name for the instance type
        description:
          type: string
          description: Description of the instance type
        logo_url:
          type: string
          description: URL to the logo of the instance type
      required:
        - id
        - name